name: mdbook
version: '0.0.28'
summary: Create book from markdown files
description: |
  mdBook is a utility to create modern online books from Markdown files.

grade: stable
confinement: strict

apps:
  mdbook:
    command: mdbook
    plugs: [network-bind, home, removable-media]

parts:
  mdbook:
    source: https://github.com/rust-lang-nursery/mdBook.git
    source-tag: 0.0.28
    plugin: rust
